FROM mdillon/postgis:9.6

RUN apt-get update && apt-get install -y "postgresql-plpython-9.6"
RUN apt-get install -y "vim"

CMD ["-c", "config_file=/etc/postgresql/postgresql.conf"]
COPY ./config/postgresql.conf /etc/postgresql/postgresql.conf
RUN chown postgres:postgres /etc/postgresql/postgresql.conf
EXPOSE 5432
